### ISSUE TITLE
There is already IPNS key with name...

### ISSUE THREAD

**Issue by xuv** [AuHau/ipfs-publish#27]
On a fresh install of `ipfs-publish`, I get this error, whatever I input there. It will always say these is an already existing key and return this 405 error.

```
There is already IPNS key with name 'ipfs_publish_<whatever_name_here>', do you want to use it? (Y/n): 
ERROR:publish.cli:HTTPError: 405 Client Error: Method Not Allowed for url: http+ip4://127.0.0.1:5001/api/v0/version?stream-channels=true
```

Anyone has experienced this? Running of Debian Buster with ipfs v 0.6.0

**Comment by xuv** [comment]
Some more info, If I do 
```
curl -X POST http://127.0.0.1:5001/api/v0/version?stream-channels=true
{"Version":"0.6.0","Commit":"","Repo":"10","System":"amd64/linux","Golang":"go1.14.4"}
```
everything seems fine. So I don't understand where the error comes from.

**Comment by xuv** [comment]
Could also be that `ipfshttpclient` needs to be updated since this is the class that seems to trigger the error in the first place.

**Comment by xuv** [comment]
I can confirm that the PR #26 (which updates `ipfsHttpClient`) fixes this issue.

**Comment by AuHau** [comment]
Thanks for the report! I will try to merge the updated dependencies and make new release by the end of the week!

**Comment by AuHau** [comment]
Sorry for the delay 🙈 I have released new patch version with updated dependencies, but I have not personally tested yet. Please let me know if it resolved your issues and if everything works as expected!

**Comment by AuHau** [comment]
Closing this issue, but if the problem persist feel free to reopen.
